In [134]:
import numpy as np
import pandas as pd

In [135]:
df = pd.read_csv('cars.csv')

In [136]:
new_df = pd.read_csv('cars.csv')

In [137]:
df.sample(5)

         brand  km_driven    fuel         owner  selling_price
6705     Honda       7032  Petrol   First Owner         779000
1343   Hyundai      63063  Petrol   First Owner         465000
1285      Tata      80000  Diesel  Second Owner         300000
2021    Maruti      50000  Petrol   First Owner         240000
7575  Mahindra      70000  Diesel  Second Owner         750000

## 1. OneHotEncoding using Pandas

In [138]:
#df = pd.get_dummies(df,columns=['fuel','owner'], dtype=int)

## 2. K-1 OneHotEncoding

In [139]:
#df = pd.get_dummies(df,columns=['fuel','owner'], dtype=int,
  #                 drop_first=True)

## 3. OneHotEncoding using Sklearn

In [140]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    df.iloc[:,0:4],df.iloc[:,-1], test_size=0.2, random_state
    =42
)

In [141]:
X_train.head(), X_test.head()

(        brand  km_driven    fuel                 owner
 6518     Tata       2560  Petrol           First Owner
 6144    Honda      80000  Petrol          Second Owner
 6381  Hyundai     150000  Diesel  Fourth & Above Owner
 438    Maruti     120000  Diesel          Second Owner
 5939   Maruti      25000  Petrol           First Owner,
        brand  km_driven    fuel         owner
 1971   Honda     110000  Petrol   Third Owner
 4664    Tata     291977  Diesel   First Owner
 5448  Maruti      70000  Diesel   First Owner
 3333   Honda     120000  Petrol  Second Owner
 2316  Maruti      69000  Diesel  Second Owner)

In [142]:
y_train.head(), y_test.head()

(6518    520000
 6144    300000
 6381    380000
 438     530000
 5939    335000
 Name: selling_price, dtype: int64,
 1971    198000
 4664    500000
 5448    425000
 3333    150000
 2316    525000
 Name: selling_price, dtype: int64)

In [143]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [144]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [145]:
df = np.hstack((X_train[['brand','km_driven']].values, X_train_new))

In [146]:
df.shape

(6502, 9)

## 4. OneHotEncoding with Top Categories

In [147]:
type(df)

numpy.ndarray

In [153]:
new_df['brand'].nunique()
threshold=100

In [154]:
counts = new_df['brand'].value_counts()

In [155]:
repl = counts[counts <= threshold].index

In [157]:
pd.get_dummies(new_df['brand'].replace(repl,'uncommon'),dtype=int)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,0,0,0,0,1,0,0,0,0,0,0,0,0
8124,0,0,0,0,1,0,0,0,0,0,0,0,0
8125,0,0,0,0,0,0,1,0,0,0,0,0,0
8126,0,0,0,0,0,0,0,0,0,1,0,0,0
8127,0,0,0,0,0,0,0,0,0,1,0,0,0