In [1]:
import pandas as pd
import requests

In [2]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=9b0f19de78193ecb444a55571e26a12f')

In [3]:
df1 = pd.DataFrame(response.json()['results'])[['id','title','overview','popularity','release_date','vote_average','vote_count']]

In [4]:
df1.head() #this df is only for 1 page

,id,title,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,43.3695,1994-09-23,8.718,30154
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",42.0565,1972-03-14,8.686,22779
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,24.3546,1974-12-20,8.571,13804
3,424,Schindler's List,The true story of how businessman Oskar Schind...,24.1763,1993-12-15,8.567,17336
4,389,12 Angry Men,The defense and the prosecution have rested an...,18.1667,1957-04-10,8.559,9903

# for 540 pages have to run a loop

In [5]:
df = pd.DataFrame() #empty dataframe

In [6]:
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
all_df = []

for i in range(1, 541):
    response = requests.get(
        f'https://api.themoviedb.org/3/movie/top_rated?api_key=9b0f19de78193ecb444a55571e26a12f&page={i}'
    )
    
    data = response.json()
    
    if 'results' in data:
        temp_df = pd.DataFrame(data['results'])[
            ['id','title','overview','popularity','release_date','vote_average','vote_count']
        ]
        all_df.append(temp_df)

df = pd.concat(all_df, ignore_index=True)

In [ ]:
df.head()

In [ ]:
df = pd.to_csv('movies.csv')