## Importing Libraries

In [2]:
import numpy as np
import pandas as pd

## 1. Opening a local csv file

In [17]:
df = pd.read_csv('placement.csv')

In [18]:
df

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

## 2. Opening a csv file from an URL

In [5]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Max OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}

req = requests.get(url)

data = StringIO(req.text)
df = pd.read_csv(data)
df.head(2)

   Country  Region
0  Algeria  AFRICA
1   Angola  AFRICA

## 3. Sep Parameter

In [6]:
tsv = pd.read_csv('all-weeks-countries.tsv',sep='\t')

In [7]:
tsv.head(2)

,country_name,country_iso2,week,category,weekly_rank,show_title,season_title,cumulative_weeks_in_top_10
0,Argentina,AR,2023-12-24,Films,1,Leave the World Behind,NaN,3
1,Argentina,AR,2023-12-24,Films,2,Rebel Moon — Part One: A Child of Fire,NaN,1

## 4. Index_col parameter 
Jab data me columns name given nhi hote tab index_col ka use karte hai

In [8]:
df2 = pd.read_csv('Countries.csv', index_col='country')

In [9]:
df2.head(2)

,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,forest_area,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,12084.4,...,41128771,27.0161,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,7889.0,...,2775634,35.7143,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister

## 5. Header Parameter 
Jab column names rows ki tarah use hote hai unhe columns me convert karne ke liye header=1 ka use karte hai

## 6. use_col parameter
Jab bahut se columns me se kuch hi columns use karne hote hai usecols ka use karte hai

In [10]:
data = pd.read_csv('Countries.csv', usecols=['country','capital_city'
                                     ,'population','title','currency'])
data.head(2)

       country        currency capital_city  population           title
0  Afghanistan  Afghan afghani        Kabul    41128771       President
1      Albania    Albanian lek       Tirana     2775634  Prime Minister

## 7. Squeeze Parameters
Jab ek hi column use karna hota hai to wo dataframe series ban jata hai

In [11]:
s = pd.read_csv('Countries.csv',usecols=['country'])['country']

In [12]:
s.head()

0    Afghanistan
1        Albania
2        Algeria
3        Andorra
4         Angola
Name: country, dtype: object

## 8. Skiprows/nrows parameter

In [13]:
df3 = pd.read_csv('Countries.csv',skiprows=[4,5])

In [14]:
df3.head(6)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.00,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.00,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.00,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Antigua and Barbuda,Antigua and Barbuda,East Caribbean dollar,Saint John's,Caribbean,Americas,Antiguan,17.05,-61.8,90.0,...,93763,11.11110,70935,22828,0.00,0.00,Unknown,31.1,Gaston Browne,Prime Minister
4,Argentina,Argentine Republic,Argentine peso,Buenos Aires,South America,Americas,Argentine,-34.00,-64.0,1083820.0,...,46234830,44.74710,3538352,42696478,2.76,7.02,Flawed democracy,27.6,Alberto Fernández,President
5,Armenia,Republic of Armenia,Armenian dram,Yerevan,Western Asia,Asia,Armenian,40.00,45.0,16760.0,...,2780469,35.51400,1012841,1767628,2.70,4.79,Hybrid regime,30.8,Nikol Pashinyan,Prime Minister

In [15]:
df4 = pd.read_csv('Countries.csv',nrows=45)

In [16]:
df4

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.00,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.50,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.00,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.20,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.00,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
5,Antigua and Barbuda,Antigua and Barbuda,East Caribbean dollar,Saint John's,Caribbean,Americas,Antiguan,17.050000,-61.800000,90.00,...,93763,11.11110,70935,22828,0.00,0.00,Unknown,31.1,Gaston Browne,Prime Minister
6,Argentina,Argentine Republic,Argentine peso,Buenos Aires,South America,Americas,Argentine,-34.000000,-64.000000,1083820.00,...,46234830,44.74710,3538352,42696478,2.76,7.02,Flawed democracy,27.6,Alberto Fernández,President
7,Armenia,Republic of Armenia,Armenian dram,Yerevan,Western Asia,Asia,Armenian,40.000000,45.000000,16760.00,...,2780469,35.51400,1012841,1767628,2.70,4.79,Hybrid regime,30.8,Nikol Pashinyan,Prime Minister
8,Australia,Commonwealth of Australia,Australian dollar,Canberra,Australia and New Zealand,Oceania,Australian,-27.000000,133.000000,3557750.00,...,25978935,38.41060,3510274,22468661,4.73,9.09,Full democracy,33.3,Anthony Albanese,Prime Minister
9,Austria,Republic of Austria,Euro,Vienna,Western Europe,Europe,Austrian,47.333333,13.333333,26467.60,...,9042528,40.98360,3684288,5358240,5.10,8.29,Full democracy,39.0,Sebastian Kurz,Federal Chancellor
10,Azerbaijan,Republic of Azerbaijan,New Azeri manat,Baku,Western Asia,Asia,Azerbaijani,40.500000,47.500000,47801.00,...,10175016,18.33330,4357959,5817057,1.32,2.65,Authoritarian,27.9,Ilham Aliyev,President
11,Bahrain,Kingdom of Bahrain,Bahraini dinar,Manama,Western Asia,Asia,Bahraini,26.000000,50.550000,86.00,...,1472233,20.00000,151007,1321226,1.28,2.71,Authoritarian,29.2,Sheikh Hamad bin Isa Al Khalifa,King
12,Bangladesh,People's Republic of Bangladesh,Bangladeshi taka,Dhaka,Southern Asia,Asia,Bangladeshi,24.000000,90.000000,99010.00,...,171186372,20.85710,103206552,67979820,1.54,5.57,Hybrid regime,22.7,Sheikh Hasina,Prime Minister
13,Barbados,Barbados,Barbados dollar,Bridgetown,Caribbean,Americas,Barbadian,13.166667,-59.533333,100.00,...,281635,26.66670,193416,88219,0.00,0.00,Unknown,35.2,Mia Mottley,Prime Minister
14,Belarus,Republic of Belarus,Belarusian rubel,Minsk,Eastern Europe,Europe,Belarusian,53.000000,28.000000,82810.00,...,9208701,40.00000,1811720,7396981,1.51,3.13,Authoritarian,36.5,Alexander Lukashenko,President
15,Belgium,Kingdom of Belgium,Euro,Brussels,Western Europe,Europe,Belgian,50.833333,4.000000,13646.10,...,11669446,42.66670,215535,11453911,6.48,7.78,Flawed democracy,37.1,Sophie Wilmès,Prime Minister
16,Belize,Belize,Belize dollar,Belmopan,Central America,Americas,Belizean,17.250000,-88.750000,1720.00,...,405272,12.50000,217242,188030,2.84,0.00,Unknown,21.6,Dean Barrow,Prime Minister
17,Benin,Republic of Benin,West African CFA franc,Porto-Novo,Western Africa,Africa,Beninese,9.500000,2.250000,39500.00,...,13352864,7.40741,6738656,6614208,2.46,5.74,Hybrid regime,13.6,Patrice Talon,President
18,Bhutan,Kingdom of Bhutan,Bhutanese ngultrum,Thimphu,Southern Asia,Asia,Bhutanese,27.500000,90.500000,5130.00,...,782455,17.39130,440632,341823,2.62,5.30,Hybrid regime,24.8,Lotay Tshering,Prime Minister
19,Bolivia,Plurinational State of Bolivia,Bolivian Boliviano,Sucre,South America,Americas,Bolivian,-17.000000,-65.000000,377870.00,...,12224110,46.15380,3565773,8658337,2.21,5.70,Hybrid regime,20.1,Jeanine Áñez,President
20,Bosnia and Herzegovina,Bosnia and Herzegovina,Bosnia and Herzegovina convertible mark,Sarajevo,Southern Europe,Europe,Bosnian,44.000000,18.000000,22160.00,...,3233526,16.66670,1621904,1611622,2.69,4.98,Hybrid regime,38.1,Valentin Inzko,High Representative
21,Botswana,Republic of Botswana,Botswana pula,Gaborone,Southern Africa,Africa,Motswana,-22.000000,24.000000,258620.00,...,2630296,11.11110,730591,1899705,3.12,7.81,Flawed democracy,19.7,Mokgweetsi Masisi,President
22,Brazil,Federative Republic of Brazil,Brazilian real,Brasília,South America,Americas,Brazilian,-10.000000,-55.000000,2368790.00,...,215313498,17.73880,26795765,188517733,2.38,6.97,Flawed democracy,29.2,Jair Bolsonaro,President
23,Brunei,Brunei Darussalam,Brunei dollar,Bandar Seri Begawan,South-Eastern Asia,Asia,Bruneian,4.500000,114.666667,134.00,...,449002,9.09091,94946,354056,1.52,0.00,Unknown,28.2,Hassanal Bolkiah,Sultan and Prime Minister
24,Bulgaria,Republic of Bulgaria,Bulgarian lev,Sofia,Eastern Europe,Europe,Bulgarian,43.000000,25.000000,50470.00,...,6465097,24.16670,1528155,4936942,2.23,7.03,Flawed democracy,40.7,Boyko Borisov,Prime Minister
25,Burkina Faso,Burkina Faso,West African CFA franc,Ouagadougou,Western Africa,Africa,Burkinabe,13.000000,-2.000000,121430.00,...,22673762,16.90140,15446047,7227715,3.19,4.75,Hybrid regime,12.9,Roch Marc Christian Kaboré,President
26,Burundi,Republic of Burundi,Burundi franc,Bujumbura,Eastern Africa,Africa,Burundian,-3.500000,30.000000,20330.00,...,12889576,38.21140,11031286,1858290,1.48,2.33,Authoritarian,11.9,Pierre Nkurunziza,President
27,Cabo Verde,Republic of Cabo Verde,Cabo Verde escudo,Praia,Western Africa,Africa,Cape Verdian,16.000000,-24.000000,790.00,...,593149,38.88890,192507,400642,3.95,7.88,Flawed democracy,22.9,NaN,NaN
28,Cambodia,Kingdom of Cambodia,Cambodian riel,Phnom Penh,South-Eastern Asia,Asia,Cambodian,13.000000,105.000000,57890.00,...,16767842,20.80000,12556766,4211076,1.70,3.59,Authoritarian,22.7,Hun Sen,Prime Minister
29,Cameroon,Republic of Cameroon,Central African CFA franc,Yaoundé,Middle Africa,Africa,Cameroonian,6.000000,12.000000,97500.00,...,27914536,33.88890,11519492,16395044,1.81,3.28,Authoritarian,13.6,Paul Biya,President
30,Canada,Canada,Canadian dollar,Ottawa,Northern America,Americas,Canadian,60.000000,-95.000000,577430.00,...,38929902,30.47340,7103929,31825973,4.98,9.15,Full democracy,36.4,Justin Trudeau,Prime Minister
31,Central African Republic,Central African Republic,Central African CFA franc,Bangui,Middle Africa,Africa,Central African,7.000000,21.000000,50800.00,...,5579144,12.85710,3173417,2405727,1.65,1.52,Authoritarian,10.8,Faustin-Archange Touadéra,President
32,Chad,Republic of Chad,Central African CFA franc,N'Djamena,Middle Africa,Africa,Chadian,15.000000,19.000000,502380.00,...,17723315,25.88830,13458554,4264761,2.13,1.61,Authoritarian,11.2,Idriss Déby,President
33,Chile,Republic of Chile,Chilean peso,Santiago,South America,Americas,Chilean,-30.000000,-71.000000,157100.00,...,19603733,35.48390,2369699,17234034,3.05,7.97,Flawed democracy,31.3,Sebastián Piñera,President
34,China,People's Republic of China,Chinese yuan,Beijing,Eastern Asia,Asia,Chinese,35.000000,105.000000,5285080.00,...,1412175000,24.94120,514596570,897578430,0.99,3.32,Authoritarian,34.5,Xi Jinping,General Secretary of the Communist Party
35,Colombia,Republic of Colombia,Colombian peso,Bogotá,South America,Americas,Colombian,4.000000,-72.000000,482428.00,...,51874024,28.87700,9311387,42562637,1.83,6.96,Flawed democracy,27.2,Iván Duque,President
36,Comoros,Union of the Comoros,Comorian franc,Moroni,Eastern Africa,Africa,Comoran,-12.166667,44.250000,1310.00,...,836774,16.66670,586880,249894,2.80,3.71,Authoritarian,16.3,Azali Assoumani,President
37,Congo,Republic of Congo,Central African CFA franc,Brazzaville,Middle Africa,Africa,Congolese,-1.000000,15.000000,106280.00,...,5970424,14.56950,1866593,4103831,2.17,3.31,Authoritarian,14.3,Denis Sassou Nguesso,President
38,Costa Rica,Republic of Costa Rica,Costa Rican colon,San José,Central America,Americas,Costa Rican,10.000000,-84.000000,17615.00,...,5180829,47.36840,930373,4250456,6.39,8.07,Full democracy,29.3,Carlos Alvarado Quesada,President
39,Côte d'Ivoire,Republic of Côte d'Ivoire,West African CFA franc,Yamoussoukro,Western Africa,Africa,Ivorian,8.000000,-5.000000,212000.00,...,28160542,14.17320,13330919,14829623,2.65,4.15,Hybrid regime,13.8,Alassane Ouattara,President
40,Croatia,Republic of Croatia,Croatian kuna,Zagreb,Southern Europe,Europe,Croatian,45.166667,15.500000,15050.00,...,3854000,31.78810,1610240,2243760,2.69,6.57,Flawed democracy,40.0,Andrej Plenković,Prime Minister
41,Cuba,Republic of Cuba,Cuban peso,Havana,Caribbean,Americas,Cuban,21.500000,-80.000000,64010.00,...,11212191,53.41300,2533843,8678348,1.23,3.00,Authoritarian,37.2,Raúl Castro,First Secretary of the Communist Party
42,Cyprus,Republic of Cyprus,Euro,Nicosia,Southern Europe,Europe,Cypriot,35.000000,33.000000,1341.29,...,1251488,14.28570,414105,837383,3.60,7.59,Flawed democracy,34.1,Nicos Anastasiades,President
43,Czech Republic,Czech Republic,Czech koruna,Prague,Eastern Europe,Europe,Czech,49.750000,15.500000,35238.70,...,10526073,25.50000,2697096,7828977,3.14,7.69,Flawed democracy,38.8,Andrej Babiš,Prime Minister
44,Dem. People's Rep. Korea,Democratic People's Republic of Korea,Democratic People's Republic of Korean won,Pyongyang,Eastern Asia,Asia,North Korean,40.000000,127.000000,25900.00,...,26069416,17.61280,9667582,16401834,0.94,1.08,Authoritarian,31.9,Kim Jong-un,Chairman of the Workers Party of Korea

## 9. Encoding Parameter

## 10. Skip bad Lines
error_bad_lines=True

## 11. dtypes parameter
to override datatype,
dtype={dict}

## 12. Handling Dates
parse_dates=['date']

## 13. Convertors

## 14. na_values parameter

## 15. Loading a huge dataset in chunks
chunksize=size